name: nest
services:
  database:
    container_name: nest-postgres-dev
    image: 'postgres:16.0-alpine3.18'
    env_file:
      - ../../.env.development
    ports:
      - '5432:5432'

  mailcatcher:
    container_name: nest-mailcatcher-dev
    image: 'sj26/mailcatcher:v0.10.0'
    ports:
      - '1080:1080' # Web UI
      - '1025:1025' # SMTP
